name: 'Therefore I am '
favicon: null
layout_spectrum: 0.7256942884996533
typography_spectrum: 0.3884576871059835
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#80A0C8'
    - '#005090'
    - '#7880A0'
    - '#D81840'
    - '#E8B0B8'
  brandStrength: 0.625
  lightness: 0.5406449695583433
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
